{% set name = "mdahole2" %}
{% set version = "0.5.0" %}

# set minimal python version according to the package (override global python_min)
# see https://github.com/MDAnalysis/mdahole2/blob/main/pyproject.toml
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 39150588b9bc07ebc176bac30d9c3b0bd25003e2e2eac24b622f2a10e5352a1f

build:
  number: 1

test:
  imports:
    - mdahole2
  requires:
    - pip
  commands:
    - pip check

outputs:
  - name: mdahole2-base
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - setuptools >=40.9.0
        - wheel
        - pip
      run:
        - python >={{ python_min }}
        - MDAnalysis >=2.0.0
        - numpy >=1.22.3
  - name: mdahole2
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - hole2
        - {{ pin_subpackage('mdahole2-base', exact=True) }}

about:
  home: https://github.com/MDAnalysis/mdahole2
  summary: 'An MDAnalysis toolkit interfacing with HOLE'
  description: |
    mdahole2 is an MDAnalysis toolkit for interfacing with
    the HOLE suite of tools to analyze an ion channel pore or
    transporter pathway as a function of time or arbitrary
    order parameters.
  license: LGPL-2.1-or-later
  license_file: LICENSE
  doc_url: https://mdanalysis.org/mdahole2
  dev_url: https://github.com/MDAnalysis/mdahole2

extra:
  recipe-maintainers:
    - lilyminium
    - IAlibay
    - orbeckst
